# COOKIES
AUTH_JWT_COOKIE_NAME = "AUTH_JWT_COOKIE"
AUTH_JWT_USER_ID_FIELD_NAME = "USER_ID"
AUTH_JWT_ACCOUNT_ID_FIELD_NAME = "ACCOUNT_ID"

# REDIS MESSAGES

REDIS_MSG_KIND_FIELD_NAME = "REDIS_MSG_KIND"
REDIS_MSG_KIND_GAME_INSTANCE_UPDATE = "REDIS_MSG_GAME_INSTANCE_UPDATE"

REDIS_MSG_DATA_FIELD_NAME_GAME_INSTANCE_ID = "REDIS_MSG_DATA_GAME_INSTANCE_ID"
REDIS_MSG_DATA_FIELD_NAME_PLAYER_IDS = "REDIS_MSG_DATA_PLAYER_IDS"

# IPC MESSAGES

IPC_TOPIC_USER_PREFIX = "IPC_TOPIC_USER:"
IPC_NOTIFICATION_KIND_FIELD_NAME = "IPC_NOTIFICATION_KIND"
IPC_NOTIFICATION_KIND_GAME_INSTANCE_UPDATE = "IPC_NOTIFICATION_GAME_INSTANCE_UPDATE"
IPC_NOTIFICATION_DATA_FIELD_NAME_GAME_INSTANCE_ID = "IPC_NOTIFICATION_DATA_GAME_INSTANCE_ID"
